### ISSUE TITLE
information details

### ISSUE THREAD

**Issue by jackphuongvu** [Samaritan1011001/Trovami#1]
Hi,. I'm just a newbie. Can you give me your database structure of Firebase?
I don't know how to set up my Firebase's database?

**Comment by Samaritan1011001** [comment]
Yes you need to set it up. I have updated the instructions to do so in the readme file.

**Comment by ZealotYew** [comment]
Hi @Samaritan1011001 ,

Can you share the Firebase database structure ? As there is no instructions in readme file.
