### ISSUE TITLE
The method 'signInWithGoogle' isn't defined for the class 'FirebaseAuth'.

### ISSUE THREAD

**Issue by ghost** [Samaritan1011001/Trovami#11]
The method 'signInWithGoogle' isn't defined for the class 'FirebaseAuth'.
Try correcting the name to the name of an existing method, or defining a method named 'signInWithGoogle'.

Screenshoot is attached. please help to get this app running

![Screenshot (7)](https://user-images.githubusercontent.com/34169886/61171339-9f1e9a00-a58f-11e9-8c2d-a5fa8f66a75e.png)

**Comment by ghost** [comment]
@Samaritan1011001

**Comment by android-imdad** [comment]
@aqibfareex replace the method with the following
  `_authenticateWithGoogle() async {
    final GoogleSignInAccount googleUser = await googleSignIn.signIn();
    final GoogleSignInAuthentication googleAuth =
    await googleUser.authentication;
    final AuthCredential credential = GoogleAuthProvider.getCredential(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );
    final FirebaseUser firebaseUser = await
    _auth.signInWithCredential(credential);
    GoogleSignInAccount user;
    setState(() {
      user = googleUser;
    });`

**Comment by emailsubjekt** [comment]
It's all red after pasting it

**Comment by emailsubjekt** [comment]
Ok, so now it's ok after pasting that, but I'm still getting this, after updating firebase in pubspec to 3.1.0 


Compiler message:
lib/signinpage.dart:115:355: Error: A value of type 'AuthResult' can't be assigned to a variable of type 'FirebaseUser'.
 - 'AuthResult' is from 'package:firebase_auth/firebase_auth.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.1/lib/firebase_auth.dart').
 - 'FirebaseUser' is from 'package:firebase_auth/firebase_auth.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.1/lib/firebase_auth.dart').
  _authenticateWithGoogle() async { final GoogleSignInAccount googleUser = await googleSignIn.signIn(); final GoogleSignInAuthentication googleAuth = await googleUser.authentication; final AuthCredential credential = GoogleAuthProvider.getCredential( accessToken: googleAuth.accessToken, idToken: googleAuth.idToken, ); final FirebaseUser firebaseUser = await _auth.signInWithCredential(credential); GoogleSignInAccount user; setState(() { user = googleUser; });
                                                                                                                                                                                                                                                                                                                                                                  ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 776

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by Samaritan1011001** [comment]
Okay, I have updated the project to fix the above errors. Although, I haven't checked it on IOS devices because I don't have a Mac but let me know if anything comes up.

**Comment by Samaritan1011001** [comment]
Closing this issue since it's been solved and also the thread and creator is inactive.
