### ISSUE TITLE
A problem occurred evaluating project ':app'. > Could not get unknown property 'keystoreProperties'

### ISSUE THREAD

**Issue by ghost** [Samaritan1011001/Trovami#12]
* Error running Gradle:
ProcessException: Process "D:\Trovami-master\android\gradlew.bat" exited abnormally:
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to C:\Users\sazar\AppData\Local\Android\sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

WARNING: The specified Android SDK Build Tools version (26.0.0-rc2) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.2.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.0-rc2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
File C:\Users\sazar\.android\repositories.cfg could not be loaded.
Checking the license for package Android SDK Build-Tools 27.0.3 in C:\Users\sazar\AppData\Local\Android\sdk\licenses
License for package Android SDK Build-Tools 27.0.3 accepted.
Preparing "Install Android SDK Build-Tools 27.0.3 (revision: 27.0.3)".
"Install Android SDK Build-Tools 27.0.3 (revision: 27.0.3)" ready.
Installing Android SDK Build-Tools 27.0.3 in C:\Users\sazar\AppData\Local\Android\sdk\build-tools\27.0.3
"Install Android SDK Build-Tools 27.0.3 (revision: 27.0.3)" complete.
"Install Android SDK Build-Tools 27.0.3 (revision: 27.0.3)" finished.
Checking the license for package Android SDK Platform 26 in C:\Users\sazar\AppData\Local\Android\sdk\licenses
License for package Android SDK Platform 26 accepted.
Preparing "Install Android SDK Platform 26 (revision: 2)".
"Install Android SDK Platform 26 (revision: 2)" ready.
Installing Android SDK Platform 26 in C:\Users\sazar\AppData\Local\Android\sdk\platforms\android-26
"Install Android SDK Platform 26 (revision: 2)" complete.
"Install Android SDK Platform 26 (revision: 2)" finished.

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Trovami-master\android\app\build.gradle' line: 42

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'keystoreProperties' for SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 10s
  Command: D:\Trovami-master\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by ghost** [comment]
@Samaritan1011001

**Comment by Samaritan1011001** [comment]
I apologize for the wait. I have corrected this and upgraded the project with the latest commit on master.However, I have not checked for IOS devices. So let me know if you get any errors there.

**Comment by Samaritan1011001** [comment]
Closing this issue since both the user and thread is inactive.
