### ISSUE TITLE
cannot work

### ISSUE THREAD

**Issue by amanasmuei** [Samaritan1011001/Trovami#2]
Running "flutter packages get" in test_app...
Package quiver has no versions that match >=0.17.0 <=0.26.2 derived from:
- flutter_test 0.0.0 depends on version 0.28.0
- uri 0.11.1 depends on version >=0.17.0 <=0.26.2
pub get failed (1)

**Comment by alexlovar** [comment]
hi, remove the develop dependencies on pubspec.yaml and package:flutter_test reference, here works on android studio 3.0.1 with flutter plugin

**Comment by Samaritan1011001** [comment]
Are you still facing the same issue?

**Comment by Samaritan1011001** [comment]
The latest code on the master has this resolved.
