### ISSUE TITLE
Maps Api key

### ISSUE THREAD

**Issue by alexlovar** [Samaritan1011001/Trovami#3]
when i click on show map, the console show an Authorization failure in the console:
E/Google Maps Android API(10834): Ensure that the following Android Key exists:
E/Google Maps Android API(10834): 	API Key: AIzaSyB4xaxweIhP0F36ZCBpfeiDjpoPc741***
But i change the main.dart MapView.setApiKey with my own Api key, and **is not the  above mentioned**
looks like this is not reading the new Api keys.
if i set
 ? MapView.setApiKey("")
      : MapView.setApiKey("");
the console still show the lines:
E/Google Maps Android API(10834): Ensure that the following Android Key exists:
E/Google Maps Android API(10834): 	API Key: AIzaSyB4xaxweIhP0F36ZCBpfeiDjpoPc741***

where is store this key to change it?

**Comment by Samaritan1011001** [comment]
Yes I forgot to mention a step. 
You'll have to add your API key in one other place.

Follow these steps:
• Open AndroidManifest.xml (/android/app/src/main/)
• Add <meta-data android:name="com.google.android.maps.v2.API_KEY" android:value="Your API key goes here inside quotes"/> along with the other meta data.

**Comment by Samaritan1011001** [comment]
Hope this helps. I am closing this for now. If your problem stills persists, reopen this :)
