### ISSUE TITLE
unable to run project

### ISSUE THREAD

**Issue by nitishk72** [Samaritan1011001/Trovami#8]
I just download this project and try to run on Android Studio.  

I set up properly but I am getting one error **createHttpClient is not defined**.

![screenshot 9](https://user-images.githubusercontent.com/15886737/46299157-63957f00-c5be-11e8-86d4-02410aabc78b.png)

I don't know that _I am doing any mistake_ or what is wrong with my project.

**Comment by Samaritan1011001** [comment]
That is because dart folks have decided to deprecate the use in that manner. I will be working on this and will release a new one in a couple of days.

**Comment by Samaritan1011001** [comment]
@nitishk72 Okay, it didn't actually take much time so you can now pull the latest master and try running it. Also, I am still upgrading the maps part of the app so showing the map feature will not work. But should be done soon.

**Comment by Samaritan1011001** [comment]
Reopen if anything else.
