### ISSUE TITLE
can't run this project because of old sdk version

### ISSUE THREAD

**Issue by aykakash** [Samaritan1011001/Trovami#9]
can't run this project because of this...

The current Dart SDK version is 2.1.0-dev.5.0.flutter-a2eb050044.

Because locate_pal requires SDK version >=1.9.0 <2.0.0, version solving failed.

pub get failed (1)
Process finished with exit code 1

**Comment by Samaritan1011001** [comment]
The latest commit resolves this issue. Please make sure you follow the readme for the entire setup and open up another issue if you have any.  
Thank you for submitting the issue.
